-- ╭──────────────────────────────────────────────────────────────────────╮
-- │  Hyprland configuration (Lua)                                        │
-- │                                                                      │
-- │  Migrated from the hyprlang .conf tree, which Hyprland deprecated in  │
-- │  0.55 and removes in 0.57. The old .conf files are still present and  │
-- │  untouched: Hyprland prefers hyprland.lua and only falls back to      │
-- │  hyprland.conf when this file is absent. To roll back, just rename    │
-- │  this file (see README-lua-migration.md).                            │
-- │                                                                      │
-- │  Load order mirrors the old `source =` order in hyprland.conf, which  │
-- │  matters: window rules apply top-to-bottom, and the first bind on a   │
-- │  key wins.                                                           │
-- ╰──────────────────────────────────────────────────────────────────────╯

require("lua.env")             -- environment variables
require("lua.settings")        -- input, misc, cursor, gestures, layouts
require("lua.decorations")     -- borders, blur, shadow, wallust colours
require("lua.animations")      -- curves + animation leaves

require("lua.windowrules")     -- vendor window/layer rules
require("lua.userwindowrules") -- your window/layer rules

require("lua.keybinds")        -- default keybinds
require("lua.userkeybinds")    -- your keybinds (loaded second, as before)
require("lua.laptops")         -- laptop keys + touchpad device

require("lua.startup")         -- exec-once equivalents

-- Generated by nwg-displays - do not edit by hand
require("monitors")
require("workspaces")
